#!/bin/sh

#SBATCH --mail-user=steven.sutcliffe@mail.mcgill.ca
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
#SBATCH --mail-type=ALL
#SBATCH --job-name=propagAte
#SBATCH --output=%x-%j.out

#SBATCH --time=12:00:00
#SBATCH --mem=2G
#SBATCH --cpus-per-task=4

source ~/Tool_Box/propagAtE/bin/activate
module load StdEnv/2020
module load bowtie2/2.4.1 samtools/1.11 scipy-stack

#Label of individual involved
ind=D

#Python script for propagate
propagate=~/Tool_Box/propagAtE/PropagAtE/PropagAtE_run.py

#Prophage coordinate file (I'm using the default one generated by VIBRANT)
prophage_coordinates=2_Prophages/VIBRANT/Ind${ind}/VIBRANT_Ind${ind}_vibrant/VIBRANT_results_Ind${ind}_vibrant/VIBRANT_integrated_prophage_coordinates_Ind${ind}_vibrant.tsv

#Output folder for each day
output_folder=2_Prophages/PropagAte/Ind${ind}

#Run propahate 6 times, once per sampling day, to see when active prophages appear
for i in {1..6}

do

#Sorted bam file for input for each day
output_bam=../2_BacterialAnalysis/7_Relative_Abundance/bowtie2/Ind${ind}/Ind${ind}_${i}_bin_sorted_coverage.bam


python3 $propagate -sb ${output_bam} -v ${prophage_coordinates} -t 4 -o ${output_folder}/Ind${ind}_${i}_propagate_result.tsv -i day_${i} -clean


done



